.TH RAD2JPEG 1 "3 March 2017" "DEVA Project"
.SH NAME
rad2jpeg \- convert RADIANCE rgbe or xyze file to a JPEG file
.SH SYNOPSIS
\." \fBrad2jpeg\fR [--exposure=stops] [--autoadjust] [--unadjusted_values]
\."	input.hdr output.jpg
\fBrad2jpeg\fR [\fIoptions\fR] {\fIinput.hdr\fR | \-} \fIoutput.jpg\fR
.SH DESCRIPTION
Convert RADIANCE rgbe or xyze file to a JPEG file.  The input can
optionally be "\-", indicating that the input image should be read from
standard input.  Pixel values in the JPEG file are adjusted to take into
account EXPOSURE records in the RADIANCE file.
.SH OPTIONS
.TP
\fB\-\-exposure=\fIstop\fR
Adjust the exposure of the output file relative to the input file,
specified in f-stops (powers  of two).  E.g., \fB\-\-exposure=+2\fR
increases the luminance in the output by a factor or four, while
\fB\-\-exposure=-1\fR decreases the luminance by half.  Fractional
values are allowed.
.TP
\fB\-\-autoadjust\fB
Auto adjust brightness values to be in an approximately displayable range.
Can be combined with \fB\-\-exposure=\fIstop\fR.
.TP
\fB\-\-unadjusted_values\fB
Use numeric pixel values in RADIANCE file, ignoring EXPOSURE records in
file header.  Sometimes this leads to brightness values in an
approximately displayable range.  Can be combined with
\fB\-\-exposure=\fIstop\fR.
.\" .SH LIMITATIONS
.SH AUTHOR
William B. Thompson
