#! /bin/bash

cd build; make clean; cd ..
rm -rf build/*

cd build-windows; make clean; cd ..
rm -rf build-windows/*

cd build-mac; make clean; cd ..
rm -rf build-mac/*

cd external-libs/zlib-1.2.11; make -f win32/Makefile.gcc clean; cd ../..
cd external-libs/libpng-1.6.34; make distclean; cd ../..
cd external-libs/jpeg-9b; make distclean; cd ../..
cd external-libs/libexif-master; make distclean; cd ../..
cd external-libs/xz-5.2.4; make distclean; cd ../..
cd external-libs/tiff-4.0.9; make clean; cd ../..
rm -rf external-libs/tiff-4.0.9/build/*
rm -rf external-libs/tiff-4.0.9/build-windows/*
rm -rf external-libs/tiff-4.0.9/build-mac/*

cd external-libs; rm  -rf macinstall/* windowsinstall/* ; cd ..
