#ifndef __RADIANCECONVERSION_VERSION_H
#define __RADIANCECONVERSION_VERSION_H

#define	RADIANCECONVERSION_VERSION		2.1.01
#define	RADIANCECONVERSION_VERSION_STRING	"2.1.01"

#endif  /* __RADIANCECONVERSION_VERSION_H */
