#ifndef __RADIANCECONVERSION_VERSION_H
#define __RADIANCECONVERSION_VERSION_H

#define	RADIANCECONVERSION_VERSION		3.0.02
#define	RADIANCECONVERSION_VERSION_STRING	"3.0.02"

#endif  /* __RADIANCECONVERSION_VERSION_H */
