#ifndef __RADIANCECONVERSION_VERSION_H
#define __RADIANCECONVERSION_VERSION_H

#define	RADIANCECONVERSION_VERSION		3.1.00
#define	RADIANCECONVERSION_VERSION_STRING	"3.1.00"

#endif  /* __RADIANCECONVERSION_VERSION_H */
