#! /bin/bash

./distclean	# This will remove Windows, Mac, and Linux builds, but
		# it's the most reliable way to insure that the CMake
		# caches are cleaned

# Build libz.a

    cd external-libs/zlib-1.2.11
    make PREFIX=x86_64-w64-mingw32- -fwin32/Makefile.gcc
    make BINARY_PATH=$PWD/../windowsinstall/bin \
    	INCLUDE_PATH=$PWD/../windowsinstall/include \
    	LIBRARY_PATH=$PWD/../windowsinstall/lib64 \
	-fwin32/Makefile.gcc \
		install
    cd ../..

# Build libpng.a

    cd external-libs/libpng-1.6.34
    ./configure \
	--host=x86_64-w64-mingw32 \
	--build=x86_64-suse-linux-gnu \
	--target=x86_64-w64-mingw32 \
	--enable-static \
	--disable-shared \
	--prefix=$PWD/../windowsinstall \
	CPPFLAGS=-I$PWD/../windowsinstall/include \
	LDFLAGS=-L$PWD/../windowsinstall/lib64
    make
    make install
    cd ../..

# Build libjpeg.a

    cd external-libs/jpeg-9b
    ./configure \
	--host=x86_64-w64-mingw32 \
	--build=x86_64-suse-linux-gnu \
	--target=x86_64-w64-mingw32 \
	--enable-static \
	--disable-shared \
	--prefix=$PWD/../windowsinstall
    make
    make install
    cd ../..

# Build libexif.a

    cd external-libs/libexif-master
    ./configure \
	--host=x86_64-w64-mingw32 \
	--build=x86_64-suse-linux-gnu \
	--target=x86_64-w64-mingw32 \
	--enable-static \
	--disable-shared \
	--prefix=$PWD/../windowsinstall \
	--disable-nls
    make
    make install
    cd ../..

# Build libtiff

    cd external-libs/tiff-4.0.9/build-windows/
    cmake -DCMAKE_TOOLCHAIN_FILE=../../Windows-toolchain.cmake \
	-DBUILD_SHARED_LIBS=OFF \
	-Djpeg=ON \
	-DCMAKE_INSTALL_PREFIX=${PWD}/../../windowsinstall/ \
	..
    make
    make install
    cd ../../..

# Build rad2jpeg rad2png rad2tiff tiff2rad tiff32_to_8

    cd build-windows
    cmake -DCMAKE_TOOLCHAIN_FILE=../Windows-toolchain.cmake ..
    make
    cd ..
